# Shell Selection
# Uncomment ONE of the following depending on which shell you want to use

# Caelestia
source = ~/.local/share/caelestia/hypr/hyprland.conf

# Ambxst
# source = ~/.local/share/ambxst/hyprland.conf

# Overrides
# source = ~/.config/hypr/ambxst-overrides.conf
