# Monitor
monitor = , preferred, auto, 1

# Scrolling
scrolling {
    column_width = 0.85
    explicit_column_widths = 0.35, 0.5, 0.65, 0.95, 1.0
}

# Animations
animations {
    animation = workspaces, 1, 5, standard, slidevert
}

# Input
input {
    kb_layout = us,ara
    kb_variant = ,
    kb_options = grp:win_space_toggle, ctrl:nocaps
    sensitivity = 0.3
    accel_profile = flat
}

# Custom apps
bind = Super, b, exec, brave-browser-nightly
bind = Super, return, exec, wezterm-gui
bind = Super+alt, k, exec, kitty
bind = ctrl+alt, b, exec, blueman-manager

# Custom controls
bind = Super+shift, w, exec, ambxst run wallpapers
bind = Super, Backslash, exec, hyprsunset -t 4500
bind = Super+Shift, Backslash, exec, pkill hyprsunset
