-- Generated by ~/.config/caelestia/scripts/wezterm-theme.py
-- DO NOT EDIT — regenerated on every wallpaper/theme change.
return {
	custom_colors = {
		red     = "#ffdff5",
		cyan    = "#e6bdbd",
		magenta = "#f8b6b7",
		yellow  = "#fecbf1",
		green   = "#B5CCBA",
	},

	status = {
		workspace  = "#bca6a6",
		mode       = "#e6bdbd",
		leader     = "#f8b6b7",
		leader_fg  = "#613335",
		cwd        = "#847171",
		process    = "#bca6a6",
		clock      = "#e6bdbd",
		battery    = "#B5CCBA",
	},

	tab_bar = {
		bg        = "#000000",
		fg        = "#f8e0df",
		gray      = "#847171",
		active_bg = "#f8b6b7",
		active_fg = "#613335",
		default_bg  = "#000000",
		default_fg  = "#f8e0df",
		hover_bg    = "#e6bdbd",
		hover_fg    = "#f8e0df",
		active_bg2  = "#ffdff5",
		active_fg2  = "#000000",
		unseen      = "#f97758",
		progress_ok = "#B5CCBA",
		progress_err = "#f97758",
		progress_ind = "#f8e0df",
	},

	terminal = {
		ansi          = { "#353434", "#ff5260", "#ffbca9", "#ffdfd9", "#b3a2d5", "#ef8f9a", "#ffba93", "#efd2cc" },
		brights       = { "#b49e9a", "#ff8486", "#ffd4c8", "#fff1ee", "#dcbc93", "#fea7ae", "#ffd1c0", "#ffffff" },
		background    = "#130c0d",
		foreground    = "#f8e0df",
		cursor_bg     = "#f8b6b7",
		cursor_fg     = "#613335",
		cursor_border = "#f8b6b7",
		selection_bg  = "#764546",
		selection_fg  = "#ffdbdb",
	},
}
