-- Generated by ~/.config/caelestia/scripts/wezterm-theme.py
-- DO NOT EDIT — regenerated on every wallpaper/theme change.
return {
	custom_colors = {
		red     = "#ffdffa",
		cyan    = "#e5bdc0",
		magenta = "#f6b6bd",
		yellow  = "#faccf5",
		green   = "#B5CCBA",
	},

	status = {
		workspace  = "#bba6a7",
		mode       = "#e5bdc0",
		leader     = "#f6b6bd",
		leader_fg  = "#603339",
		cwd        = "#837172",
		process    = "#bba6a7",
		clock      = "#e5bdc0",
		battery    = "#B5CCBA",
	},

	tab_bar = {
		bg        = "#000000",
		fg        = "#f8e0e1",
		gray      = "#837172",
		active_bg = "#f6b6bd",
		active_fg = "#603339",
	},

	terminal = {
		ansi          = { "#353434", "#ff516d", "#ffbcae", "#ffdedb", "#b3a2d5", "#ee8fa2", "#ffba93", "#efd2ce" },
		brights       = { "#b49e9c", "#ff838f", "#ffd4ca", "#fff1ef", "#dcbc93", "#fda7b5", "#ffd1c0", "#ffffff" },
		background    = "#130c0d",
		foreground    = "#f8e0e1",
		cursor_bg     = "#f6b6bd",
		cursor_fg     = "#603339",
		cursor_border = "#f6b6bd",
		selection_bg  = "#75454b",
		selection_fg  = "#ffdadd",
	},
}
