hl.on("hyprland.start", function()
    hl.exec_cmd("qs -c end4-pC")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("wl-paste --type text --watch bash -c 'cliphist store && qs -c end4-pC ipc call cliphistService update'")
    hl.exec_cmd("wl-paste --type image --watch bash -c 'cliphist store && qs -c end4-pC ipc call cliphistService update'")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
