# ### DMS Variables ###

# Apps
$terminal = wezterm-gui
$browser = brave-browser-nightly
$editor = codium
$fileExplorer = thunar

# Input
$sensitivity = 0.3
$accelProfile = flat
$kbLayout = us,ara
$kbOptions = grp:win_space_toggle, ctrl:nocaps

# Gaps
$gapsIn = 4
$gapsOut = 8
$borderSize = 2

# Decoration
$rounding = 12
$blurEnabled = true

# DMS IPC
$dmsCmd = dms ipc call
