local M = {}

-- All hexes come from theme.lua (generated by ~/.config/caelestia/scripts/wezterm-theme.py).
function M.apply(config, constants)
	local t = constants.theme.tab_bar
	local tr = constants.theme.terminal

	config.colors = {
		-- Terminal ANSI overrides (overrides the base color_scheme).
		ansi = tr.ansi,
		brights = tr.brights,
		background = tr.background,
		foreground = tr.foreground,
		cursor_bg = tr.cursor_bg,
		cursor_fg = tr.cursor_fg,
		cursor_border = tr.cursor_border,
		selection_bg = tr.selection_bg,
		selection_fg = tr.selection_fg,

		tab_bar = {
			background = t.bg,
			active_tab = {
				bg_color = t.active_bg,
				fg_color = t.active_fg,
				intensity = "Bold",
				underline = "None",
			},
			inactive_tab = {
				bg_color = t.bg,
				fg_color = t.gray,
			},
			inactive_tab_hover = {
				bg_color = t.gray,
				fg_color = t.fg,
			},
			new_tab = {
				bg_color = t.bg,
				fg_color = t.fg,
			},
		},
	}
end

return M
