$primary = c2c1ff
$onPrimary = 2a2a60
$primaryContainer = 7171ac
$onPrimaryContainer = ffffff
$secondary = c6c4e0
$onSecondary = 2e2e44
$secondaryContainer = 45455c
$onSecondaryContainer = b4b2ce
$tertiary = f5b2e0
$onTertiary = 4e1e44
$tertiaryContainer = bb7da9
$onTertiaryContainer = 000000
$background = 131317
$onBackground = e5e1e7
$surface = 131317
$onSurface = e5e1e7
$surfaceVariant = 47464f
$onSurfaceVariant = c8c5d1
$surfaceContainer = 201f23
$surfaceContainerHigh = 2a292e
$surfaceContainerHighest = 353438
$surfaceContainerLow = 1c1b1f
$surfaceContainerLowest = 0e0e12
$outline = 918f9a
$outlineVariant = 47464f
$shadow = 000000
$scrim = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
