-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        layout = "scrolling",
    },
    gestures = {
        workspace_swipe_touch = true,
    },
    input = {
        touchpad = {
            natural_scroll = true,
        },
    },
    scrolling = {
        column_width = 0.69,
    },
})
