$background = 121414
$onBackground = e3e2e2
$surface = 121414
$surfaceDim = 121414
$surfaceBright = 38393a
$surfaceContainerLowest = 0d0e0f
$surfaceContainerLow = 1a1c1c
$surfaceContainer = 1e2020
$surfaceContainerHigh = 292a2a
$surfaceContainerHighest = 343535
$onSurface = e3e2e2
$surfaceVariant = 424849
$onSurfaceVariant = c1c7c9
$outline = 8b9293
$outlineVariant = 424849
$inverseSurface = e3e2e2
$inverseOnSurface = 2f3131
$shadow = 000000
$scrim = 000000
$surfaceTint = afcbd2
$primary = afcbd2
$primaryDim = d9f6fd
$onPrimary = 19343a
$primaryContainer = 7a959c
$onPrimaryContainer = 001216
$inversePrimary = 486368
$primaryFixed = cbe8ee
$primaryFixedDim = afcbd2
$onPrimaryFixed = 021f24
$onPrimaryFixedVariant = 314b50
$secondary = bec8cb
$secondaryDim = dae4e7
$onSecondary = 283234
$secondaryContainer = 3e484b
$onSecondaryContainer = acb7ba
$secondaryFixed = dae4e7
$secondaryFixedDim = bec8cb
$onSecondaryFixed = 131d1f
$onSecondaryFixedVariant = 3e484b
$tertiary = cfc1dc
$tertiaryDim = ebddf9
$onTertiary = 352d41
$tertiaryContainer = 988ca5
$onTertiaryContainer = 130c1f
$tertiaryFixed = ebddf9
$tertiaryFixedDim = cfc1dc
$onTertiaryFixed = 20182b
$onTertiaryFixedVariant = 4c4358
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 617c82
$secondaryPaletteKeyColor = 6e797b
$tertiaryPaletteKeyColor = 82778f
$neutralPaletteKeyColor = 777777
$neutralVariantPaletteKeyColor = 72787a
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 617c82
$secondary_paletteKeyColor = 6e797b
$tertiary_paletteKeyColor = 82778f
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 72787a
$term0 = 343434
$term1 = 8383ff
$term2 = 42e1da
$term3 = 75fcdd
$term4 = 77b4bf
$term5 = 7aaee9
$term6 = 80d7da
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 04f6ee
$term11 = c9fff3
$term12 = a4c7cb
$term13 = a2c0f7
$term14 = 87ebed
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 6fcbf7
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f3
$green = 8af0f3
$teal = 9fecf6
$sky = 95e8f8
$sapphire = 75d4eb
$blue = 62caeb
$lavender = 8dd7f5
$klink = 0094b0
$klinkSelection = 0094ae
$kvisited = 008abb
$kvisitedSelection = 008ab8
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bcc3
$kpositiveSelection = 00bcc1
$text = e3e2e2
$subtext1 = c1c7c9
$subtext0 = 8b9293
$overlay2 = 797f80
$overlay1 = 676c6c
$overlay0 = 565a5b
$surface2 = 454949
$surface1 = 353838
$surface0 = 232626
$base = 121414
$mantle = 121414
$crust = 111313
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
