$background = 0e0e0e
$onBackground = e5e5e5
$surface = 0e0e0e
$surfaceDim = 0e0e0e
$surfaceBright = 2c2c2c
$surfaceContainerLowest = 000000
$surfaceContainerLow = 131313
$surfaceContainer = 1a1a1a
$surfaceContainerHigh = 202020
$surfaceContainerHighest = 262626
$onSurface = e5e5e5
$surfaceVariant = 262626
$onSurfaceVariant = ababab
$outline = 767676
$outlineVariant = 474747
$inverseSurface = f9f9f9
$inverseOnSurface = 555555
$shadow = 000000
$scrim = 000000
$surfaceTint = c7c7c7
$primary = c7c7c7
$primaryDim = b9b9b9
$onPrimary = 404040
$primaryContainer = 474747
$onPrimaryContainer = d0d0d0
$inversePrimary = 5f5f5f
$primaryFixed = e2e2e2
$primaryFixedDim = d5d5d5
$onPrimaryFixed = 3f3f3f
$onPrimaryFixedVariant = 5b5b5b
$secondary = 9d9d9d
$secondaryDim = 9d9d9d
$onSecondary = 202020
$secondaryContainer = 3b3b3b
$onSecondaryContainer = bfbfbf
$secondaryFixed = e3e3e3
$secondaryFixedDim = d5d5d5
$onSecondaryFixed = 3f3f3f
$onSecondaryFixedVariant = 5c5c5c
$tertiary = f1f1f1
$tertiaryDim = e9e0e6
$onTertiary = 5e595d
$tertiaryContainer = e9e0e6
$onTertiaryContainer = 565055
$tertiaryFixed = e9e0e6
$tertiaryFixedDim = dbd2d8
$onTertiaryFixed = 433d43
$onTertiaryFixedVariant = 60595f
$error = d78890
$errorDim = a76068
$onError = 3f0f17
$errorContainer = 71333c
$onErrorContainer = e8a2a9
$primaryPaletteKeyColor = 777777
$secondaryPaletteKeyColor = 777777
$tertiaryPaletteKeyColor = 777777
$neutralPaletteKeyColor = 777777
$neutralVariantPaletteKeyColor = 777777
$errorPaletteKeyColor = ab626a
$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 777777
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$term0 = 343434
$term1 = ef5e8b
$term2 = e3c5c3
$term3 = e6e6e6
$term4 = afa6bd
$term5 = d49aae
$term6 = e6c2af
$term7 = d8d8d8
$term8 = a3a3a3
$term9 = eb8da4
$term10 = e2dcdb
$term11 = f4f4f4
$term12 = c9bfb6
$term13 = e2b3c0
$term14 = e2d9d6
$term15 = ffffff
$rosewater = f1f1f1
$flamingo = e2e2e2
$pink = e7dadd
$mauve = ebafcd
$red = e7a0b6
$maroon = dbb4be
$peach = e5c6c9
$yellow = f1f1f1
$green = e3dfde
$teal = e1dee6
$sky = e3d6e8
$sapphire = e3bbe0
$blue = e2add2
$lavender = ebc1da
$klink = a778a0
$klinkSelection = a7789f
$kvisited = b26991
$kvisitedSelection = b36991
$knegative = d75f8c
$knegativeSelection = d75f8a
$kneutral = ea91a3
$kneutralSelection = ea91a2
$kpositive = ed9450
$kpositiveSelection = ed9450
$text = e5e5e5
$subtext1 = ababab
$subtext0 = 767676
$overlay2 = 676767
$overlay1 = 585858
$overlay0 = 494949
$surface2 = 3b3b3b
$surface1 = 2d2d2d
$surface0 = 1d1d1d
$base = 0e0e0e
$mantle = 0e0e0e
$crust = 0d0d0d
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
