$background = 130d0b
$onBackground = f9e0db
$surface = 130d0b
$surfaceDim = 130d0b
$surfaceBright = 372926
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a110f
$surfaceContainer = 221715
$surfaceContainerHigh = 291d1a
$surfaceContainerHighest = 302220
$onSurface = f9e0db
$surfaceVariant = 302220
$onSurfaceVariant = bca6a2
$outline = 84716d
$outlineVariant = 554441
$inverseSurface = fff8f6
$inverseOnSurface = 5d5351
$shadow = 000000
$scrim = 000000
$surfaceTint = f9b7a9
$primary = f9b7a9
$primaryDim = eaa99c
$onPrimary = 61342a
$primaryContainer = 76453b
$onPrimaryContainer = ffdbd4
$inversePrimary = 855247
$primaryFixed = fcb9ab
$primaryFixedDim = edac9e
$onPrimaryFixed = 4b221a
$onPrimaryFixedVariant = 6e3e34
$secondary = e7bdb4
$secondaryDim = d8afa7
$onSecondary = 563933
$secondaryContainer = 51342e
$onSecondaryContainer = dfb6ad
$secondaryFixed = ffdad3
$secondaryFixedDim = f6cbc2
$onSecondaryFixed = 553832
$onSecondaryFixedVariant = 74544d
$tertiary = ffe4c0
$tertiaryDim = fed494
$onTertiary = 6d501d
$tertiaryContainer = fed494
$onTertiaryContainer = 644715
$tertiaryFixed = fed494
$tertiaryFixedDim = efc688
$onTertiaryFixed = 4f3503
$onTertiaryFixedVariant = 6e511e
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = a0695d
$secondaryPaletteKeyColor = 926f68
$tertiaryPaletteKeyColor = 92713b
$neutralPaletteKeyColor = 807472
$neutralVariantPaletteKeyColor = 86736f
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = a0695d
$secondary_paletteKeyColor = 926f68
$tertiary_paletteKeyColor = 92713b
$neutral_paletteKeyColor = 807472
$neutral_variant_paletteKeyColor = 86736f
$term0 = 353433
$term1 = ff5638
$term2 = ffbd9b
$term3 = ffdfd4
$term4 = b9ab66
$term5 = f28f87
$term6 = ffba8b
$term7 = efd2c8
$term8 = b49e97
$term9 = ff866e
$term10 = ffd4c0
$term11 = fff1ed
$term12 = dcbc93
$term13 = ffa99e
$term14 = ffd2b7
$term15 = ffffff
$rosewater = ffeeea
$flamingo = ffd9d3
$pink = ffd2d0
$mauve = ffa9ae
$red = ff988c
$maroon = faaa9f
$peach = ffbfac
$yellow = ffeee7
$green = ffd8c0
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbbc5
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5c63
$kvisitedSelection = cf5c64
$knegative = eb5540
$knegativeSelection = eb5541
$kneutral = ff8a68
$kneutralSelection = ff8a69
$kpositive = fc8c27
$kpositiveSelection = fc8c28
$text = f9e0db
$subtext1 = bca6a2
$subtext0 = 84716d
$overlay2 = 74635f
$overlay1 = 635450
$overlay0 = 534643
$surface2 = 443836
$surface1 = 342b28
$surface0 = 241c1a
$base = 130d0b
$mantle = 130d0b
$crust = 120c0a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
